theme: minima
title: "github page!"
baseurl: /skills-github-pages-pub
description: "github pages test hhh"
future: true
nav:
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/