theme: minima
title: "github page!"
description: "github pages test"
future: true
nav:
  - title: "Home"
    url: /
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/

# Set a custom permalink structure for posts:
permalink: /blog/:title/
