theme: minima
title: "github page!"
baseurl: /skills-github-pages-pub
description: "github pages test nnn"
future: true
nav:
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/
  - title: "Team"
    url: /team/
  - title: "NOAA"
    url: /noaa/
  - title: "Search"
    url: /search/
  